name: main-workflow
on: workflow_dispatch
jobs:
  run-e2e-macos:
    name: run-e2e-macos
    runs-on: macos-latest
    env:
      CI_MAC_OS: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: 'Run test'
        working-directory: e2e-tests/interface-tests-playwright
        run: |
          npx playwright install
          npx playwright test -c ./playwright.config.ts

  # run-e2e:
  #   name: run-e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.SUBMODULE_TOKEN }}
  #         submodules: true
  #     - uses: pnpm/action-setup@v4
  #       with:
  #         version: 9
  #     - run: pnpm install
  #     - run: pnpm nx e2e interface-tests-playwright --skip-nx-cache
  #     - name: Archive production artifacts
  #       if: failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: dist-without-markdown
  #         path: |
  #           e2e-tests/interface-tests-playwright/src/tests
